export const newsObjOne= { 
    bgColour: "purple",
    lightText: true,
    lightTextDescription: true,
    headline: "Programs and Registration",
    description: "As a bridge between home and formal schooling, we offer a treasured early learning expereince in an engaging, inclusive, social setting.",
    buttonLabel: "Read More",
    buttonLink: "/Programs",
    buttonColour: "whiteBtn",
    imgStart: "start",
    img: "/images/RideauCanalFieldTrip.jpg",
    img2: "/images/KindergartenRoom_1.jpg",
    img3: "/images/SchoolAgeRoom.jpg",
    title: "Preschool Program",
    title2: "Kindergarten Program",
    title3: "School Age Program",
    subtitle: "2.5 to 5 years of age",
    subtitle2: "4 to 5 years of age",
    subtitle3: "6 to 12 years of age",
    alt: ""
}